name: Build and Release

on:
  release:
    types:
      - created

jobs:
  release:
    name: Build and Release for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          - target: x86_64-unknown-linux-musl
            archive: tar.xz
          - target: x86_64-unknown-linux-musl
            archive: tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Debug matrix information
        run: |
          echo "Building for target: ${{ matrix.target }}"
          echo "Using archive type: ${{ matrix.archive }}"

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.target }}-${{ matrix.archive }}
          path: target/
